---
- hosts:
    - asanova_gcp_selenoid-vm-1
    - asanova_gcp_selenoid-vm-2
  become: yes
  remote_user: root
  roles:
    - geerlingguy.docker
    - robertdebock.python_pip
    - { role: ../selenoid-docker }
